apiVersion: v1
kind: Secret
metadata:
  name: myapp-secret
type: Opaque
data:
  username: dXNlcm5hbWUxMjM=  # base64-encoded value for "username123"
  password: cGFzc3dvcmQxMjM=  # base64-encoded value for "password123"
